### PR TITLE
adding date input range

### PR DESCRIPTION
**Pull request by MayaGans**
So I changed the input to `dateRangeInput` BUT because renderTable and renderDataTable render dates as numerics I can't *really* tell if the actual filtering logic works. Would you mind looking into the filtering code (I'm using the same logic as the numeric inputs, might not be okay - hard to check though)

Screen Shot 2020-04-09 at 9 41 53 AM

### CODE REVIEW

**Comment by MayaGans** [comment]
With some sleuthing it does seem to be working! [I checked to see that there are 37 dates in 2014 and filtered to only include 2014 and it worked.... thoughts?]

**Comment by AARON-CLARK** [comment]
I will pull and take a look!

**Comment by AARON-CLARK** [comment]
Definitely seems to be working as intended. While I had the code pulled, I added a min/max for the dateRangeInput so users can't select dates outside the min/max values. Is that okay @MayaGans ?

**Comment by MayaGans** [comment]
Looks great! Merging.

**Pull request merged**
